backend:
  name: git-gateway
  branch: main

site_url: https://donut-software.com

media_folder: "public/blog-images"
public_folder: "/blog-images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss.000Z"}
      - {label: "Author", name: "author", widget: "string", default: "Yuki Tachi"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
